export const env = {
    PORT:                   Number(process.env.PORT) || 3001,
    NODE_ENV:               process.env.NODE_ENV || 'development',
    DATABASE_URL:           process.env.DATABASE_URL!,
    JWT_ACCESS_SECRET:      process.env.JWT_ACCESS_SECRET!,
    JWT_ACCESS_TTL:         process.env.JWT_ACCESS_TTL || '15m',
    REFRESH_TOKEN_TTL_DAYS: Number(process.env.REFRESH_TOKEN_TTL_DAYS) || 30,
    LLM_PROVIDER: (process.env.LLM_PROVIDER || 'ollama') as 'ollama' | 'gemini' | 'euri',
    OLLAMA_HOST:  process.env.OLLAMA_HOST  || 'http://localhost:11434',
    OLLAMA_MODEL: process.env.OLLAMA_MODEL || 'qwen2.5-coder:7b',
    GEMINI_API_KEY: process.env.GEMINI_API_KEY || '',
    GEMINI_MODEL:   process.env.GEMINI_MODEL   || 'gemini-2.5-flash',
    EURI_API_KEY:  process.env.EURI_API_KEY  || '',
    EURI_BASE_URL: process.env.EURI_BASE_URL || 'https://api.euron.one/api/v1/euri',
    EURI_MODEL:    process.env.EURI_MODEL    || 'gpt-5.3-instant',
    CORS_ORIGIN: process.env.CORS_ORIGIN || 'http://localhost:3000',
    VERCEL_TOKEN:          process.env.VERCEL_TOKEN          || '',
    VERCEL_TEAM_ID:        process.env.VERCEL_TEAM_ID        || '',
    VERCEL_PROJECT_ID:     process.env.VERCEL_PROJECT_ID     || '',
    // C++ runtime snapshot (g++ preinstalled). Built once via build-cpp-snapshot.ts; empty until then.
    VERCEL_CPP_SNAPSHOT_ID: process.env.VERCEL_CPP_SNAPSHOT_ID || '',
    SANDBOX_TIMEOUT_MS:    Number(process.env.SANDBOX_TIMEOUT_MS)    || 5_000,
    SANDBOX_MAX_OUTPUT_KB: Number(process.env.SANDBOX_MAX_OUTPUT_KB) || 64,
    MAX_GENERATED_CASES:   Number(process.env.MAX_GENERATED_CASES)   || 6,
}